version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(ci)"
  - package-ecosystem: "terraform"
    directory: "cloud"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(cloud)"
