keys:
  - &aws arn:aws:kms:us-east-1:415471498952:key/1b9d4b5e-3193-459d-99ea-50e3a0d6fd2d
  - &tom age1dujf55uzev2nnpq6c2drn0e8pmpxay22qqfsavwaxqakwn9se5hsputgx4
creation_rules:
  - path_regex: vault.yaml
    key_groups:
      - age:
          - *tom
        kms:
          - arn: *aws
